# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa1ee6970a005d17a7cf1ff0423cd0a6e06869244fe6423954b829b1355ce24afd192dc1064528a5de127712f2e1a505cce03661c9b9944f8e70d70e6ba01e3d

test:
  secret_key_base: 2a0eb4a54b76cc89e99cdc9e972b3c10fc657073e822d45903e6dea06e9450e2ed6209e9ec5a95f995aa9feba8f31baf0ca87e7d8118b6591b73e6815cd0dc62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
